### ISSUE TITLE
Feature request: With friends now gone, a way to see what a certain account is watching

### ISSUE THREAD

**Issue by HiP3X** [CommanderRoot/twitch-tools#10]
An option to see what an account is watching, maybe check the live channels said accounts follow and check if they are in their chat.

**Comment by CommanderRoot** [comment]
There are a few issues with implementing such a tool.

1. There is no official 3rd party API for getting the users connected to a chat.
2. Using unofficial APIs you can get only 1 channel per request.

In regards to 1.:
As there is no official API, Twitch doesn't want external services to use this data. Using the unofficial APIs could get you into trouble with Twitch.

In regards to 2.:
Because a user can follow up to 2000 channels you would need up to that many requests to lookup all followed channels (of course it's never that many as not that many follow so many accounts and also not that many are online at the same time). But even if it's just a few hundred such a "lookup" would take quite some time.


You could just lookup and keep a record of all currently live channels in the background and store it in a DB.  This would make checking where a single account is very fast but with over 100k live channels regularly that's a lot of requests as well. You would also have to at least scan the channels every 10 - 15 minutes to be up to date enough.

So either way you do it, it would be a lot of requests towards unofficial APIs which could get you into trouble from Twitch. Not to mention all the privacy complains from users if you could basically "stalk" them without any opt-in or opt-out like the friends list had.
