### ISSUE TITLE
[Feature] Twitch Stream Filter: Support for tag and charity filtering

### ISSUE THREAD

**Issue by Infinitay** [CommanderRoot/twitch-tools#109]
Would it be possible for you to add support for filtering by channel/stream tags used and also by the current active charity on a stream within your [Twitch Stream Filter tool](https://twitch-tools.rootonline.de/channel_previews.php)? 

see: https://dev.twitch.tv/docs/api/reference/#get-charity-campaign

**Comment by CommanderRoot** [comment]
Tags searching / filtering is not something I'm willing to build due to the shortcomings they have (https://github.com/CommanderRoot/twitch-tools/issues/42#issuecomment-1510016346)

The charity API you linked requires the broadcasters authorisation and also only allows one channel per request. Each of these issues alone makes usage impossible for the scale of all channels.

**Comment by Infinitay** [comment]
Understandable, thanks for looking into it and apologies for the duplicate request. When I searched for tags I believe Refined GitHub extension appends ` is:open` by default to searches and I didn't think to remove it at the time.

**Comment by CommanderRoot** [comment]
Not a problem at all. It's been quite some time since then so it could have been possible that things have changed
