### ISSUE TITLE
Twitch stream filter no longer showing small streamers

### ISSUE THREAD

**Issue by bxssl** [CommanderRoot/twitch-tools#11]
I use the low to high viewers filter because I prefer watching streamers that I can actually communicate with unlike big streamers, however, this filter is suddenly no longer working, it shows big streamers only.
I hope this issue is temporary but I still wanted to bring it to your attention.

**Comment by gabrielgnd1** [comment]
Yep, had this issue on me. Apparently it only shows minimum of 200 views and no less than that

**Comment by bxssl** [comment]
The issue seems to have been fixed now @gabrielgnd1

**Comment by CommanderRoot** [comment]
This issue is related to a continues [DDOS attack](https://twitter.com/CommanderRoot/status/1533159612144312321) which is happening for about a week but only really caused issues the past 3 days.
Basically the script updating this data times out and aborts after a certain number of failed requests. Sometimes this means no update at all (stale data) or it means just getting a few top streams and missing low viewer ones.
