### ISSUE TITLE
[Request - Twitch Emote Search by name] Add support for searching for emote prefixes and/or sorting for search results

### ISSUE THREAD

**Issue by MGrand3** [CommanderRoot/twitch-tools#23]
The ability to search emote prefixes (or add a wildcard symbol for 'any uppercase letter' maybe?) would make figuring out which emote prefixes are available (bar ones that are assigned to a streamer who doesn't have any emotes currently) a lot easier.

Not sure if it's possible to separate prefixes and emote names entirely since numbers can exist in both, but it would be a very handy tool for aspiring partners planning for a prefix change in the near future.

Also, the ability to sort alphabetically would make it a lot easier to scan through search results. May be a good feature regardless of how viable prefix searches are.

**Comment by CommanderRoot** [comment]
With the way the search currently works having the ability to use "wildcards" is not possible, at least not in a performant way.

As you have said due to the prefix having the ability to have a number at the end and a suffix being able to start with a number it's not really possible to know the prefix just from looking at the emote token.

I have changed the sorting of the emotes from "somewhat random" to sorting by emote token. This should help somewhat for your case. It will also help group emotes from the same channel together.

Imo the best thing you can do to find if an emote prefix is used is to use these options:

- Starts with
- your lowercase string you want to search
- case sensitive

**Comment by MGrand3** [comment]
That does actually help a lot. Thanks!
