### ISSUE TITLE
block / ban list tool breaks when resolving specific username

### ISSUE THREAD

**Issue by Tofuraven** [CommanderRoot/twitch-tools#37]
For some reason, the block and ban list tools seem to break during name resolution when trying to add a username containing `adver` - instead of the "new blocks/bans have been added" message they respond with `Error while resolving usernames, please try again. (0, error, )`.
The issue is reproducible by inserting any word with that term in it into the "add username" field (it doesn't matter whether the word is an existing username or not).
If that username is part of a list, none of the other names in the list get added either, and the tool has to be reloaded before it's possible to add users again.

**Comment by CommanderRoot** [comment]
I can't reproduce this issue on my end but I have a good guess about what's causing it.
The error `0` means it was a timeout or the request never reached the server for some other reason. This lets me believe that an adblocker in this case is blocking the request because it matches one of their rules.
You could try disabling it for the tools page and see if the issue still persists.

**Comment by Tofuraven** [comment]
Good call. I did test it in multiple browsers and ruled that out automatically without thinking about it, but in a completely clean browser environment it doesn't occur.
