### ISSUE TITLE
Feature Request: Ability to search channels via tags

### ISSUE THREAD

**Issue by seanenriquez** [CommanderRoot/twitch-tools#42]
Not sure if twitch exposes this in their API but it would be cool to be able to search by tags. For some reason when I search by tags the thumbnails take literal minutes to all load in chrome unlike in twitch-tools.

**Comment by CommanderRoot** [comment]
#24 had this request already.
I did implement the display of tags on the tools page since then (not that bad). I also explored filtering by tags shortly after.
Quite a bit of page load time is caused by the current 4,185 different games you can filter by. Now you look at the currently (at night / non Twitch peak) 71,418 different tags and that's a quick disaster waiting to happen. There are also multiple tags with the same spelling and different casings so that doesn't make it better either.
