### ISSUE TITLE
Unfollow

### ISSUE THREAD

**Issue by PSingletary** [CommanderRoot/twitch-tools#58]
With the limit of 2000 follows, what channel to follow management is klunky at best.
(similar to follower_remover)

1. get a list of all the channels i follow
2. last time channel was live
3. last time i was subbed
4. link to their emotes
5. selector box to unfollow all or most

**Comment by CommanderRoot** [comment]
1. The [following list viewer](https://twitch-tools.rootonline.de/followinglist_viewer.php) lets you do that
2. Twitch doesn't return this information in any of their public APIs
3. The public Twitch API can only tell you if you're currently subbed or not (and at what tier). It doesn't tell you if you subbed in the past, how long the sub will last or what your sub streak is
4. I've now added a link to the channels emotes on the [following list viewer](https://twitch-tools.rootonline.de/followinglist_viewer.php)
5. Twitch removed the ability for 3rd parties to manage (add or remove) follows on July 27, 2021. Since then you can only add or remove follows via the normal website or the Twitch mobile app
