### ISSUE TITLE
Following list viewer

### ISSUE THREAD

**Issue by DTJohnson5** [CommanderRoot/twitch-tools#62]
Currently, when I open the Twitch-tools site to check a users following list, it defaults to my username and there is no option to check another user.

**Comment by CommanderRoot** [comment]
That's not a bug but rather due to a change by Twitch. On Sep 12th Twitch changed the permissions for viewing the follower / follow lists.
Since then:
- Only you can view who you follow
- Only you and your moderators can view who follows you

[https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769](https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769)
