### ISSUE TITLE
[Feature Request] Following List - select channels to unfollow

### ISSUE THREAD

**Issue by h3oCharles** [CommanderRoot/twitch-tools#72]
there are already existing tools that can unfollow every channel. but what if i dont want to unfollow every single channel? i'd like to unfollow channels by certain criteria, or by selecting them myself (perhaps a checkmark to the left of their name)

some criteria could be:
- when was the last time they streamed
- when was the last time i chatted in their channel
- when was the last time i visited their channel when they were live (idk if this can be tracked at all)
- do they have any videos in past broastcasts. if so, what games/categories are in these videos

i have a very old twitch account that's has reached 2000 channels followed (if i attempt to follow someone, the follow button lights back up), and there's no easy way to unfollow specific channels without opening the following list, middle clicking every channel i'd like to unfollow, waiting for the channel to load, just to press the unfollow button, confirmation, and close the tab

**Comment by CommanderRoot** [comment]
Managing (adding or removing) follows hasn't been possible for 3rd parties since [July 27, 2021](https://discuss.dev.twitch.com/t/deprecation-of-create-and-delete-follows-api-endpoints/32351). You can "work around" the removing part by using blocking which also removes the follows but has the other "negative" effects of blocking. This means you will always have to go to the channel on the website or mobile app to unfollow it.

As for the filtering of followed channels to make it easier to find the channels you might want to unfollow:

> - when was the last time they streamed
> - when was the last time i chatted in their channel
> - when was the last time i visited their channel when they were live (idk if this can be tracked at all)

Sadly Twitch doesn't provide this information via any of their public APIs

> - do they have any videos in past broastcasts. if so, what games/categories are in these videos

This would be possible to check. However as past broadcasts get deleted after [7, 14 or 60](https://help.twitch.tv/s/article/video-on-demand?language=en_US#enabling) days (depending on account type / turbo) and quite a few channels don't have it enabled at all this probably wouldn't tell you much.

**Comment by h3oCharles** [comment]
oof

**Comment by h3oCharles** [comment]
oof

**Comment by CommanderRoot** [comment]
![grafik](https://github.com/CommanderRoot/twitch-tools/assets/4395417/cd46a914-e8f5-4e54-bad9-478d49f95741)
I have added and option to check the last VOD date on the following list viewer

**Comment by h3oCharles** [comment]
> this probably wouldn't tell you much

oh, you'd be surprised, here's a fragment of the bottom of my following list... it's all over the place
given that i just want to do a quick purge of my following list (cuz i hit the cap of 2000 following), this is more than enough food for unfollows

![image](https://github.com/CommanderRoot/twitch-tools/assets/8020330/e282323b-ba5b-4513-9890-ffb0e785f642)
