### ISSUE TITLE
Mutual automatic blocking

### ISSUE THREAD

**Issue by dorian50l** [CommanderRoot/twitch-tools#75]
Hello, I still have a problem.
I was automatically banned/blocked on the Twitch channel (darkblast_tv) that I started following on January 4th. Plus, he's now on my blocked list even though I haven't done anything?
Can you help me please ?
In case I give you my twitch name: dorian50l (it's the letter L at the end but in lower case)
Thanks !

**Comment by CommanderRoot** [comment]
Looks like you (dorian50l) are using my "[block all new followers](https://twitch-tools.rootonline.de/block_all_new_followers.php)" tool since 2023-12-30.
darkblast_tv tried to follow you on 2024-01-04 (most likely to follow you back) and because of the use of my tool it then blocked him. This removed their follow to you and your follow to them. That's also why their account is now on your blocklist.
