### ISSUE TITLE
Falsely tagged as bot

### ISSUE THREAD

**Issue by betrayedjinn** [CommanderRoot/twitch-tools#80]
Hello everyone,
it seems, that my friend [baldur1976](https://www.twitch.tv/baldur1976) has been wrongly flagged as a bot and is prevented from following some channels.
Can you please remove him from the bot list?

Thank you.

**Comment by CommanderRoot** [comment]
Duplicate of #30

The mentioned account was on the list in the past but was already removed from it for over a year after it was reported as "not a bot". It was added because it was part of one or multiple follow bot raids, for example against [https://www.twitch.tv/lltoxiic](https://www.twitch.tv/lltoxiic)
